### ISSUE TITLE
Wrong url in module.json

### ISSUE THREAD

**Issue by Boefjim** [League-of-Foundry-Developers/foundryvtt-forien-unidentified-items#10]
in src/module.json
`"url": "https://github.com/Forien/foundryvtt-forien-unidentified-items",`
should be
`"url": "https://github.com/League-of-Foundry-Developers/foundryvtt-forien-unidentified-items",`

People are reporting bugs in the wrong repo (the manifest file can't be found atm)

**Comment by Varriount** [comment]
Unless I'm reading things incorrectly, [this is already the case](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-unidentified-items/blob/master/src/module.json#L20).

**Comment by Boefjim** [comment]
I mean [line 19](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-unidentified-items/blob/master/src/module.json#L19), which still references the original repo

**Comment by CMDRLucienn** [comment]
Fixing this url will fix the following link:
![image](https://user-images.githubusercontent.com/7802122/134818864-38418631-f8e2-4ac4-a038-eb2d41b3c30b.png)
Which still needs to be done; however, it won't fix the fact that Foundry isn't able to update this module.

The issue stems from there not being a module.json in the root folder of the repo ([this url](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-unidentified-items/blob/master/src/module.json#L20))

The module .json is located at `/src/module.json` currently and manually modifying the manifest to this location allows it to be updated/installed, but unless this is fixed, it'll require a manual edit every time.

**Comment by Boefjim** [comment]
Yeh, that is a seperate issue that should definitely also be resolved.
I tried to fix both locally and then push it on a new branch to create a merge request but it seems the repo isn't publically editable?
In any case fixing both urls would be best yeh, and maybe there could be a copy of the module.json at the root of the repo to point at the new manifest file for a few weeks so people can update it to the proper path without having to do so manually.
