### ISSUE TITLE
[BUG] Does not appear to work with Foundry V10

### ISSUE THREAD

**Issue by imobe001** [League-of-Foundry-Developers/foundryvtt-forien-unidentified-items#30]
**Module Version:** v0.5.4

**Describe the bug**
Cannot install in V10, requires older version

**To Reproduce**
Attempt to install via automatic module add-on or via manifest URL.

**Expected behavior**
Module installs

**Screenshots**
Error Message:
setup.js:292 Error: module forien-unidentified-items version 0.5.4 requires an older version of 
      the Foundry Virtual Tabletop software: 9 or older
    at Module.installPackage (file:///C:/Program%20Files/FoundryVTT/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:1882)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SetupView.handlePost (file:///C:/Program%20Files/FoundryVTT/Foundry%20Virtual%20Tabletop/resources/app/dist/server/views/setup.mjs:1:1980)

**Foundry Version:** 
V10.284

**Game System:** 
DnD5e

**Comment by DivertedCircle** [comment]
0.5.5 is giving the same error when trying to install.

**Comment by VestOfHolding** [comment]
0.5.6 is also flagged as verified for V9. Any ETA or general wheels turning for V10 support?

**Comment by Varriount** [comment]
Hm, 0.5.6 *should* allow being installed (and should work) on v10, though FoundryVTT may warn about possible incompatibility. I haven't had confirmation about whether it actually works on v10 yet, which is why it hasn't been confirmed.

**Comment by RoyRandom** [comment]
On foundry 10, When I try to mystify as...I cannot drag an item or anything to represent the image.

**Comment by gubacelar** [comment]
The module will be updated to v10?

**Comment by Varriount** [comment]
If someone submits a PR for V10 compatibility, I will review and merge it. Until then, compatibility will be V9 only.

**Comment by amir-arad** [comment]
> If someone submits a PR for V10 compatibility, I will review and merge it. Until then, compatibility will be V9 only.

Someone has taken the time to migrate this to v10 but did not submit a PR.
https://github.com/League-of-Foundry-Developers/foundryvtt-forien-unidentified-items/compare/master...p4535992:foundryvtt-forien-unidentified-items:master
