### ISSUE TITLE
Compatible for V10

### ISSUE THREAD

**Issue by Weskernation** [League-of-Foundry-Developers/foundryvtt-forien-unidentified-items#35]
Items can still be Mystified, and checked. however to Identify an item (click the Pink icon) does not work in V10

**Comment by Fridan99** [comment]
It seems that it doesn't work very well in v10

**Comment by germandrewboat** [comment]
Any update on this getting v10 compatibility from the League?

**Comment by subatoiWolf** [comment]
I am asso very interested in getting this to work with foundry vtt v10

**Comment by Fridan99** [comment]
someone to rescue this fabulous module? 🙂

**Comment by MB1997** [comment]
Some other v10 bugs I experienced:

1. Turn a world item mystic and then view it, Updates the world items name and icon, but not its Mystic State. 
Same for Owned items. 

2. turning an owned item Mystic, seems to bug the item. it cannot be identified but viewed.

**Comment by Varriount** [comment]
So, just to clear things up: compatibility with V10 is unlikely to come from the maintainers, *HOWEVER* we will happily review any PRs that implement it.
