### ISSUE TITLE
0.8.x Support

### ISSUE THREAD

**Issue by justinrpurdy** [League-of-Foundry-Developers/foundryvtt-forien-unidentified-items#4]
There's currently no other built-in feature or module to replicate this functionality.

**Comment by erlendaakre** [comment]
Would be great to see this module updated

**Comment by marcottedan** [comment]
I agree, but it doesn't seem supported by Forien anymore, it looks like being kept alive by the League of Foundry Developers.

**Comment by Jedi005** [comment]
Agreed. I'm not moving the 0.8.x until we have an update, or similar function in another module.

**Comment by Varriount** [comment]
Migrating to 0.8.x isn't hard - it's generally more a matter of renaming than anything else.

**Comment by Jedi005** [comment]
Maybe I'm misunderstanding... Isn't there a functionality issue with this mod in 0.8.x?  "Basic functionality is working, but Advanced Demystify and Demystify as windows are non-functional"

**Comment by Varriount** [comment]
The functionality issue is likely caused by incorrect property/function/class names being referenced by the module. Between 0.7.x and 0.8.x, large parts of Foundry's API were renamed and restructured. While there are some backwards compatibility shims in Foundry's API, they don't cover all the changes.

**Comment by ravingdragoon** [comment]
@Varriount @League-of-Foundry-Developers Can someone take a look at the pull requests pending for this module to get the it up to date?

**Comment by anthonyronda** [comment]
@justinrpurdy and others: ok to close? See #5
